### PR TITLE
docs updates

### PR DESCRIPTION
**Pull request by funkyfuture**
hopefully this will solve some doc issues. just ping me if there are issues after merging.

builds overview: https://readthedocs.org/projects/cerberus/builds/

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
looks like we aren't quite there yet https://readthedocs.org/projects/cerberus/builds/6961279/

**Comment by funkyfuture** [comment]
a'ight, i added a fix for that in the same branch.

**Comment by nicolaiarocci** [comment]
Works like a charm. A link is missing (or was it intentional) at the first 'external resource' reference. You made me laugh at the second one 😄

**Comment by funkyfuture** [comment]
ah, thanks. pushed another commit with the link.

you know, everyone outside italy thinks that a 'cc'  is a hard k, while at the same time is able to properly pronounce capuccino. the trans-alpine barbarians need training on that issue.

**Pull request merged**
