### PR TITLE
Adds the 'contains' rule

### PR DESCRIPTION
**Pull request by funkyfuture**
pretty straight-forward, isn't it?

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Screw it, since we were going to break semver with 1.2.x, we can as well go ahead and release the new stuff with that same version. Then we can go back to the regular workflow. Please let me merge until everything is sorted out.

**Comment by nicolaiarocci** [comment]
rebased and merged

**Comment by nicolaiarocci** [comment]
We might actually release this as 1.3 and be done with it :-)

**Comment by funkyfuture** [comment]
> since we were going to break semver with 1.2.x

how were we? with #388? i'd consider documentation clarifications as bugfixes.

**Comment by nicolaiarocci** [comment]
the drop of Python 2.6 and 3.3 support.

**Comment by funkyfuture** [comment]
was that in the `1.2.x` branch? though for my understanding of [the release policy](https://github.com/pyeve/cerberus#versioning--interpreter-support) the drop of tested interpreters doesn't mean a minor branch has to be dropped. we 'just' can't test it. and we shouldn't release major releases whenever we can't test an interpreter anymore. as we still need to document git maintenance and release flows, we could think about including non-public, local tests based on Docker images into that.

now that this branch is deleted, we could still assemble a proper one.

**Comment by nicolaiarocci** [comment]
Yes, it was in `1.2.x`. I agree that we can branch and cherry-pick useful stuff from master. Also, a `1.3` long-running branch might be doable too, as long as we keep it rebased on top of master, so it can be easily merged at due time (yes, we can force-push that one). I will try to find the time and write down the desired git workflow in the coming days.

**Comment by funkyfuture** [comment]
i'll see that i make my [multi-interpreter environment](https://hub.docker.com/r/funkyfuture/nest-of-serpents/) for Docker fit for the old interpreters w/ old pip versions in the next days. but i wouldn't use that on Travis, that would be much heavier regarding needed resources.

**Comment by nicolaiarocci** [comment]
I wouldn't worry too much about dropped pythons. Let's just wave goodbye to them 😄

**Pull request closed without merging**
