### PR TITLE
Creating testcase featuring strange behaviour

### PR DESCRIPTION
**Pull request by txomon**
Following #225, I found a validator issue that I don't fully understand.

The main idea of the new test case file is to create end to end test cases. Feature use cases that have been broken in some point in the history, so that no regression happens.

### CODE REVIEW

**Comment by txomon** [comment]
I must say that I have no idea on how to fix it. My guess is that anyof together with schema doesn't work quite well.

Just in case, check also the schema correctness...

**Comment by funkyfuture** [comment]
i agree, the should be more complex testcases. though i recently removed one. but i think it's better put on hold until a `1.0`.

however when identifying and solving bugs i prefer the least complex setup.

> Just in case, check also the schema correctness...

well, it makes not much sense as you provide only one variant for `anyof`. is this intended?

to get an idea of what may be wrong, the output of this test would be useful. i'm currently focussed on something else when i have the time to work on cerberus, hence i won't look into it too soon..

please have a look at `TestBase`.

**Comment by txomon** [comment]
You have the output in the CI server, will copy it ASAP.

Probably I didn't express myself correctly, I wanted to add regression test
cases, which sometimes are complex.

In this case I reduced the example to a bare minimum to expose the bug.

Looks like there is a recursion bug on constraint checking, but I really
can't tell

**Comment by funkyfuture** [comment]
nope, the interesting part is here: `AttributeError: 'Validator' object has no attribute '_validate_type_required'`

which means that cerberus wants to validate a type that isn't implemented. this is caused by the ambiguity of `schema`. it /should/ work when you define a `'type': 'list'` beside the first `schema`-rule.

see #168 and 7dc632866a2ea6956dc65f42d03e3ab45c295605.

if you find anything to improve the situation, it's highly appreciated.

**Comment by funkyfuture** [comment]
@txomon is this still stomething that needs to be addressed? after rebasing on top of master's HEAD.

**Comment by txomon** [comment]
Sorry, I am unable to book time for this :/ I will have a look on it if I step again on it.

**Pull request closed without merging**
