### PR TITLE
Added second overall benchmark (not tested)

### PR DESCRIPTION
**Pull request by msotnikov**
According https://github.com/pyeve/cerberus/issues/517
The PR contain documents for benchmarking. Please check it.

### CODE REVIEW

**Comment by funkyfuture** [comment]
thank you, i already made some fixes locally to get it working.

am i missing something, or are the objects `ProductNormalizer`, `GroupNormalizer` and `group_schema` used at all?

**Comment by msotnikov** [comment]
> thank you, i already made some fixes locally to get it working.
> 
> am i missing something, or are the objects `ProductNormalizer`, `GroupNormalizer` and `group_schema` used at all?

Yes, they never used.
`ProductNormalizer`, `GroupNormalizer` replaced with TestValidator and can be removed freely.
group_schema is the second type of document that can be in data set.

**Comment by msotnikov** [comment]
> thank you, i already made some fixes locally to get it working.
> 
> am i missing something, or are the objects `ProductNormalizer`, `GroupNormalizer` and `group_schema` used at all?

Can you push these fixes to get this PR closed?

**Comment by funkyfuture** [comment]
okay, i got on that again. can you confirm that the `group_schema` isn't required at all?

**Comment by funkyfuture** [comment]
i merged the benchmark into the `master` and the `1.3.x` branch.

**Pull request closed without merging**
