### PR TITLE
allow to set update=True  at instanciation

### PR DESCRIPTION
**Pull request by jgirardet**
This is to  have the same two instances but with different behaviour.
Needed if we can't access to validation parameter at validate call.

This PR keeps the standard behaviour unchanged

### CODE REVIEW

**Comment by funkyfuture** [comment]
i think you could easily achieve that by subclassing `Validator` as there's a mechanism to store arbritrary initialization values:

```python

class MyValidator(cerberus.Validator):
    def validate(self, *args, **kwargs):
        kwargs['update'] = self._config['update']
        super().validate(*args, **kwargs)
```

**Comment by jgirardet** [comment]
ok, that  solves the probleme.
however I think it's costless enhancement to add it by default, but maybe  there are some design choice I'm not aware.
Anyway thank you for your answer  and cerberus !

**Comment by jgirardet** [comment]
Sorry but your proposal  doesn't work by me : 

``` python
import cerberus

class MyValidator(cerberus.Validator):
    def validate(self, *args, **kwargs):
        kwargs['update'] = self._config['update']
        super().validate(*args, **kwargs)


schema = {
    "a": {"type":"string", "required":True},
    "b": {"type":"string"},
}

val = MyValidator(schema)
valup = MyValidator(schema, update = True)

valid = {'a':'hello', 'b':"hello"}
invalid = {'b':"hello"}


print(val(valid))
print(val(invalid))
print(valup(valid))
print(valup(invalid))

"""
>>> True
>>> False
>>> True
>>> False      # Should be True, if working
"""
```

**Comment by jgirardet** [comment]
ok after some tests, It doesn't work if y ou call validate or __call__ but it's ok with validated

**Comment by jgirardet** [comment]
it's ok if I  don't use validate()  or __call_  but validated  :thinking:

**Comment by jgirardet** [comment]
If you aren't intrested in it maybe we could close it.
I finally use  your subclass trick and call the data with validated() and it's good like that : 
https://github.com/jgirardet/apistar-cerberus/blob/master/apistar_cerberus/apistar_cerberus.py
thanks for herlp

**Pull request closed without merging**
